name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main   # or "master" if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Ruby for Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'   # Works well with Jekyll
          bundler-cache: true

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll site
      - name: Build site
        run: bundle exec jekyll build --trace

      # Deploy built site to GitHub Pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
